<?php

return [
    'categories' => [
        'getting-started' => 'Primeiros passos',
        'operation' => 'Operação',
        'assessment' => 'Avaliação & Debrief',
        'governance' => 'Histórico & Governança',
    ],

    'audiences' => [
        'instructor',
        'evaluator',
        'manager',
        'administrator',
    ],

    'articles' => [
        [
            'slug' => 'getting-started',
            'file' => 'getting-started.md',
            'title' => 'Primeiros passos',
            'summary' => 'Entenda o contexto autenticado, a navegação e o ciclo cenário → execução → avaliação → histórico.',
            'category' => 'getting-started',
            'audience' => ['instructor', 'evaluator', 'manager', 'administrator'],
            'tags' => ['início', 'navegação', 'organização ativa', 'ciclo'],
            'order' => 10,
            'reviewed_on' => '2026-08-09',
            'related' => ['scenarios-and-versioning', 'execution-cockpit'],
            'contextual_for' => ['dashboard'],
        ],
        [
            'slug' => 'scenarios-and-versioning',
            'file' => 'scenarios-and-versioning.md',
            'title' => 'Cenários e versionamento',
            'summary' => 'Veja como rascunho, publicação, revisão, templates e versões preservam a definição usada em cada execução.',
            'category' => 'operation',
            'audience' => ['instructor', 'manager'],
            'tags' => ['cenários', 'versões', 'publicação', 'templates'],
            'order' => 20,
            'reviewed_on' => '2026-08-09',
            'related' => ['getting-started', 'execution-cockpit'],
            'contextual_for' => ['scenarios.index', 'scenarios.show', 'scenario-templates.index'],
        ],
        [
            'slug' => 'execution-cockpit',
            'file' => 'execution-cockpit.md',
            'title' => 'Cockpit de execução',
            'summary' => 'Entenda lifecycle, equipes, participantes, recursos, injects e a timeline histórica append-only da execução.',
            'category' => 'operation',
            'audience' => ['instructor', 'evaluator'],
            'tags' => ['execução', 'cockpit', 'timeline', 'injects', 'recursos'],
            'order' => 30,
            'reviewed_on' => '2026-08-09',
            'related' => ['scenarios-and-versioning', 'assessment-and-debrief'],
            'contextual_for' => ['executions.show'],
        ],
        [
            'slug' => 'assessment-and-debrief',
            'file' => 'assessment-and-debrief.md',
            'title' => 'Avaliação e debrief',
            'summary' => 'Navegue pela rubrica, evidências, observações, debrief, plano de ação e finalização histórica da avaliação.',
            'category' => 'assessment',
            'audience' => ['evaluator', 'instructor', 'manager'],
            'tags' => ['avaliação', 'debrief', 'rubrica', 'evidências', 'ações'],
            'order' => 40,
            'reviewed_on' => '2026-08-09',
            'related' => ['execution-cockpit', 'history-and-reports'],
            'contextual_for' => ['assessments.show'],
        ],
        [
            'slug' => 'history-and-reports',
            'file' => 'history-and-reports.md',
            'title' => 'Histórico e relatórios',
            'summary' => 'Compreenda histórico, dashboards, verdade de avaliação e exportações CSV/PDF dentro do contexto autorizado.',
            'category' => 'governance',
            'audience' => ['instructor', 'evaluator', 'manager', 'administrator'],
            'tags' => ['histórico', 'relatórios', 'dashboard', 'csv', 'pdf'],
            'order' => 50,
            'reviewed_on' => '2026-08-09',
            'related' => ['assessment-and-debrief', 'people-organizations-access'],
            'contextual_for' => ['execution-history.index', 'dashboard.executive'],
        ],
        [
            'slug' => 'people-organizations-access',
            'file' => 'people-organizations-access.md',
            'title' => 'Pessoas, organizações e acessos',
            'summary' => 'Entenda organização ativa, unidades, memberships, funções, abilities e a diferença entre UX e autorização backend.',
            'category' => 'governance',
            'audience' => ['manager', 'administrator'],
            'tags' => ['pessoas', 'organizações', 'acessos', 'memberships', 'abilities'],
            'order' => 60,
            'reviewed_on' => '2026-08-09',
            'related' => ['getting-started', 'history-and-reports'],
            'contextual_for' => ['people.index', 'organizations.index', 'access.index'],
        ],
    ],
];
